# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

# Modified to matrix test across three OS and two Temurin distributions of Java - two LTS versions (11 and 17)

name: transpose-matrix-test

on:
  pull_request:
    branches: [ "master", "dev", "transpose-matrix" ]

permissions:
  contents: read

jobs:
  build:
    name: Build on node ${{ matrix.java_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java_version: ['11', '17']
        os: [ ubuntu-latest, windows-latest, macOS-latest ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.java_version }} on ${{ matrix.os }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java_version }}
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
  
